In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
diabetes_diabetic_df=pd.read_csv('/home/student/Documents/Data Set/dataset_diabetes_diabetic_data.csv')

In [3]:
diabetes_diabetic_df.head(200)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2601576,279009,Caucasian,Female,[60-70),?,6,25,1,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
196,2602860,511965,Caucasian,Female,[60-70),?,6,25,7,4,...,No,Down,No,No,No,No,No,Ch,Yes,NO
197,2629110,2283327,AfricanAmerican,Female,[40-50),?,6,25,1,6,...,No,Up,No,No,No,No,No,Ch,Yes,<30
198,2638410,6225435,Caucasian,Female,[30-40),?,6,25,1,4,...,No,No,No,No,No,No,No,No,No,NO
199,2652750,100605564,Caucasian,Male,[20-30),?,2,6,2,10,...,No,No,No,No,No,No,No,No,No,>30

In [4]:
diabetes_diabetic_df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [5]:
diabetes_diabetic_df['max_glu_serum'].fillna(diabetes_diabetic_df['max_glu_serum'].mode()[0], inplace=True)

In [6]:
diabetes_diabetic_df['max_glu_serum'].isnull().value_counts()

max_glu_serum
False    101766
Name: count, dtype: int64

In [7]:
from sklearn.impute import KNNImputer

In [8]:
pip install --upgrade pip

Requirement already satisfied: pip in ./jupyter-env/lib/python3.8/site-packages (24.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
diabetes_diabetic_df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [10]:
from sklearn.impute import KNNImputer

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
categorical_columns = diabetes_diabetic_df.select_dtypes(include=['object']).columns

In [13]:
print("Categorical columns:", categorical_columns)

Categorical columns: Index(['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty',
       'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin',
       'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride',
       'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [14]:
encoder = OneHotEncoder(sparse_output=False, drop='first')

In [15]:
encoded_columns = encoder.fit_transform(diabetes_diabetic_df[categorical_columns])

In [16]:
encoded_df = pd.DataFrame(encoded_columns, columns=encoder.get_feature_names_out(categorical_columns))

In [17]:
dataset_with_encoded = pd.concat([diabetes_diabetic_df.drop(columns=categorical_columns), encoded_df], axis=1)

In [18]:
imputer = KNNImputer(n_neighbors=25)

In [19]:
imputed_data = imputer.fit_transform(dataset_with_encoded)

In [20]:
imputed_df = pd.DataFrame(imputed_data, columns=dataset_with_encoded.columns)

In [21]:
print("Missing values after imputation", imputed_df.isnull().sum())

Missing values after imputation encounter_id                     0
patient_nbr                      0
admission_type_id                0
discharge_disposition_id         0
admission_source_id              0
                                ..
metformin-pioglitazone_Steady    0
change_No                        0
diabetesMed_Yes                  0
readmitted_>30                   0
readmitted_NO                    0
Length: 2437, dtype: int64

In [22]:
diabetes_diabetic_df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
column_to_encode = 'A1Cresult'

In [25]:
label_encoder = LabelEncoder()

In [26]:
diabetes_diabetic_df[column_to_encode] = label_encoder.fit_transform(diabetes_diabetic_df[column_to_encode])

In [27]:
diabetes_diabetic_df['A1Cresult'].isnull().value_counts()

A1Cresult
False    101766
Name: count, dtype: int64

In [29]:
categorical_features = diabetes_diabetic_df.select_dtypes(include=['object']).columns

In [31]:
cardinality = {feature: diabetes_diabetic_df[feature].nunique() for feature in categorical_features}

In [33]:
threshold = 10

In [34]:
high_cardinality_features = {feature: count for feature, count in cardinality.items() if count > threshold}

In [35]:
print(high_cardinality_features)

{'payer_code': 18, 'medical_specialty': 73, 'diag_1': 717, 'diag_2': 749, 'diag_3': 790}

In [36]:
def reduce_cardinality(diabetes_diabetic_df, column, threshold=0.01):
    freq = diabetes_diabetic_df[column].value_counts(normalize=True)
    categories_to_keep = freq[freq > threshold].index.tolist()
    diabetes_diabetic_df[column] = diabetes_diabetic_df[column].apply(lambda x: x if x in categories_to_keep else 'Other')

In [39]:
reduce_cardinality(diabetes_diabetic_df, 'payer_code', threshold=0.01)

In [40]:
print(diabetes_diabetic_df['payer_code'].value_counts())

payer_code
?        40256
MC       32439
HM        6274
SP        5007
BC        4655
MD        3532
CP        2533
UN        2448
CM        1937
Other     1652
OG        1033
Name: count, dtype: int64

In [41]:
reduce_cardinality(diabetes_diabetic_df, 'medical_specialty', threshold=0.01)

In [42]:
print(diabetes_diabetic_df['medical_specialty'].value_counts())

medical_specialty
?                             49949
InternalMedicine              14635
Other                          8340
Emergency/Trauma               7565
Family/GeneralPractice         7440
Cardiology                     5352
Surgery-General                3099
Nephrology                     1613
Orthopedics                    1400
Orthopedics-Reconstructive     1233
Radiologist                    1140
Name: count, dtype: int64

In [43]:
def combine_categories(diabetes_diabetic_df, column, categories_to_combine, new_category_name):
    diabetes_diabetic_df.loc[diabetes_diabetic_df[column].isin(categories_to_combine), column] = new_category_name
    return diabetes_diabetic_df

In [46]:
diabetes_diabetic_df = combine_categories(diabetes_diabetic_df, 'diag_1', ['diag_2', 'diag_3'], 'diagnosis')

In [48]:
cleaned_data = diabetes_diabetic_df.head(200)
cleaned_data

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2601576,279009,Caucasian,Female,[60-70),?,6,25,1,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
196,2602860,511965,Caucasian,Female,[60-70),?,6,25,7,4,...,No,Down,No,No,No,No,No,Ch,Yes,NO
197,2629110,2283327,AfricanAmerican,Female,[40-50),?,6,25,1,6,...,No,Up,No,No,No,No,No,Ch,Yes,<30
198,2638410,6225435,Caucasian,Female,[30-40),?,6,25,1,4,...,No,No,No,No,No,No,No,No,No,NO
199,2652750,100605564,Caucasian,Male,[20-30),?,2,6,2,10,...,No,No,No,No,No,No,No,No,No,>30